/**:
  ros__parameters:
    traffic_light_signal_timeout: 1.0

    planning_hz: 10.0
    backward_path_length: 5.0
    forward_path_length: 300.0
    backward_length_buffer_for_end_of_pull_over: 5.0
    backward_length_buffer_for_end_of_pull_out: 5.0
    minimum_pull_over_length: 16.0

    refine_goal_search_radius_range: 7.5

    # parameters for turn signal decider
    turn_signal_intersection_search_distance: 30.0
    turn_signal_intersection_angle_threshold_deg: 15.0
    turn_signal_minimum_search_distance: 10.0
    turn_signal_search_time: 3.0
    turn_signal_shift_length_threshold: 0.3
    turn_signal_remaining_shift_length_threshold: 0.1
    turn_signal_on_swerving: true

    enable_akima_spline_first: false
    enable_cog_on_centerline: false
    input_path_interval: 2.0
    output_path_interval: 2.0

    # parameters for roundabout
    turn_signal_roundabout: 
      on_entry: "None" # "None", "Left", "Right", "TowardsExit"
      entry_indicator_persistence: true # whether to keep the indicator on after entering the roundabout
      towards_exit:
        straight_angle_th: [160.0, 200.0] # [min, max] 
        enable_left_turn_indicator_only_first_exit: true
      on_exit: "Left" # "None", "Left", "Right",